[package]
name = "wasmo-llvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
llvm-sys = "130.0"

[lib]
path = "lib/lib.rs"
