[package]
name = "wasmo-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmo-runtime = { path = "../wasmo-runtime" }
wat = "1.0.41"
env_logger = "0.9.0"

[lib]
path = "lib.rs"
